import React from 'react';
import './App.css';
import Box from './Box'
export default class Appr extends React.Component{
 state={
    //this array will contain all the prompts entered by the user
    prmpts:[],
    //this array will contain all the outputs generated by the API
    outs:[]
  }
  //function to append the user prompts to the array
  UpdatePrompts=(e)=>{
  this.setState({prmpts:[...this.state.prmpts,e.value]})
  }
  //function to append the Ai output to the output array
  UpdateOutput=(e)=>{
    this.setState({outs:[...this.state.outs,e]})
  }

  //This is the function that will be triggered by the Submit button
  async fun1(){
    //Here we handel the input by the user 
    console.log(process.env.REACT_APP_OPENAIKEY)
    const inp = document.getElementById('textarea');
    //call function to store user input in array
    this.UpdatePrompts(inp);
    // Here we make the API calls
    const data = {
      //here we make the call with the user's input 
      prompt: inp.value,
      temperature: 0.5,
      max_tokens: 90,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
     };
      const resp = await fetch("https://api.openai.com/v1/engines/text-curie-001/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: process.env.REACT_APP_OPENAIKEY,
      },
      body: JSON.stringify(data),
     });
      const ans = await resp.json();
      //call function to store API response array
      //API returns data in JSON format hence we decompose it to retrive the info we want to display
      this.UpdateOutput(ans.choices[0].text)
      
      //clear value for new input 
      inp.value = "";
  }
  //Here we render the component
  render(){
    return(
      <>
        
        <h1 className='title'>Prompt:</h1>
        <div id="form">
          <textarea 
            placeholder="Enter prompt here:&#10;For Example: 'Write a poem about dogs'"
            id="textarea">
          </textarea>
          <br/>
          <input type="button" id="presets-btn" value="Presets"/>
          <input type="button" id="submit-btn" value="Submit" onClick={this.fun1.bind(this)} />
      </div>
      {/* A map function will be used to iterate thorough both arrays, output array is iterated using the 'i'
      (counter generated by function) and prompts array is iterated using the itarator (item) itself */}
      <h1 className='title' id='response-title'>Responses:</h1>
      {/* We use the Box component to render each response and input, we use the slice(0).reverse(0) functions to display the output in newest to oldest */}
      {this.state.prmpts.slice(0).reverse().map((item,i)=>
      <Box
        key={i}
        usrprmpt={item}
        output={this.state.outs.slice(0).reverse()[i]}>
      </Box>
      )}  
     </>
    )
  }
}